### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/DSCI_522_group27#102]
Hello,

Great work on this project!  The project is very well described and documented.  Very interesting topic as well, there is so much subjectivity in wine quality!  

I have a few small comments/suggestions:

Analysis and reasoning:
- You introduce R^2 as the scoring metric but then include negative mean squared error and negative mean absolute error in all the score tables.  I would suggest introducing all the scoring metrics viewed, why they were considered, why R^2 was chosen compared to the others, etc..  Alternatively you could remove the additional metrics from the tables.   
- The report often refers to the "test scores" when you are referring to the cross validation score, I would suggest using "validation scores" instead. 

Code:
- I had some issues running the make file.  I received this error `raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)`.  Creating a yaml file for the required environment could simplify recreating the analysis for another user. 
- The scripts look great, very clearly documented. 

Good luck with the rest of your project! 
Elanor

**Comment by Tammy1128** [comment]
Thanks for your feedback, and we solved them. Good luck as well with the rest of your project!
